apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  creationTimestamp: null
  name: artemiskameletxpath
spec:
  flows:
  - route:
      from:
        parameters:
          brokerURL: '{{artemis_url}}'
          destinationName: '{{workday_source_queue}}'
          password: '{{artemis_password}}'
          username: '{{artemis_user}}'
        steps:
        - setHeader:
            name: CamelAwsS3Key
            xpath:
              expression: /company/name
              resultType: java.lang.String
        - log:
            message: ${headers}
        uri: kamelet:jms-pooled-apache-artemis-source
  traits:
    camel:
      runtimeVersion: 3.15.2
    container:
      image: ghcr.io/rmortale/default/camel-k-kit-cv1k1gka56ms73e8g93g@sha256:932d8f560eb23f4638f63b5a6ba553fa7e7513af71b91e40b40ab40ec26f92d2
    jvm:
      classpath: dependencies/*:dependencies/app/*:dependencies/lib/boot/*:dependencies/lib/main/*:dependencies/quarkus/*
    kamelets:
      list: jms-pooled-apache-artemis-source,sink
    mount:
      configs:
      - configmap:artemis-creds
      - configmap:workday-config
    pull-secret:
      imagePullerDelegation: false
      secretName: registry
status: {}
