apiVersion: v1
kind: ConfigMap
metadata:
  name: file-sender-cm
data:
  application-do-not-commit.properties: |
    ### local testing values
    # Kafka
    app.bootstrapServers=144.24.252.7:9092
    app.topicNames=minio-events
    app.consumerGroup=file-sender-group3
    app.localDir=/tmp


    # minio download props
    camel.component.aws2-s3.uri-endpoint-override=http://144.24.252.7:9000
    camel.component.aws2-s3.override-endpoint=true
    camel.component.aws2-s3.region=us-east-1
    camel.component.aws2-s3.force-path-style=true
    camel.component.aws2-s3.operation=getObject



