apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: file-sender
spec:
  dependencies:
  - camel:jq
  flows:
  - route:
      from:
        id: from-kafka
        parameters:
          bootstrapServers: '{{app.bootstrapServers}}'
          consumerGroup: '{{app.consumerGroup}}'
          topic: '{{app.topicNames}}'
        steps:
        - setHeaders:
            headers:
            - expression:
                jq:
                  expression: header("kafka.KEY") | split("/")[1:] | join("/")
              name: CamelAwsS3Key
            - expression:
                jq:
                  expression: header("kafka.KEY") | split("/")[0]
              name: CamelAwsS3OverrideBucketName
            id: extract file names
        - log: 'file: ${header.CamelAwsS3Key} - bucket: ${header.CamelAwsS3OverrideBucketName}'
        uri: kamelet:kafka-not-secured-source
      id: filesender-route
  traits:
    camel:
      runtimeVersion: 3.15.2
    container:
      image: ghcr.io/rmortale/camel-k/camel-k-kit-cvnvo0afki5c73bl2vtg@sha256:64bf97cfb2e355c172463c503ea3b815141f268e511d99a2edc7355aee82db9e
    jvm:
      classpath: dependencies/*:dependencies/app/*:dependencies/lib/boot/*:dependencies/lib/main/*:dependencies/quarkus/*
    kamelets:
      list: kafka-not-secured-source,sink
    mount:
      configs:
      - configmap:file-sender
    pull-secret:
      imagePullerDelegation: false
      secretName: registry-secret
status: {}
