apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: file-sender
spec:
  flows:
  - route:
      from:
        id: from-kafka
        parameters:
          bootstrapServers: '{{app.bootstrapServers}}'
          consumerGroup: '{{app.consumerGroup}}'
          topic: '{{app.topicNames}}'
        steps:
        - setHeaders:
            id: extract file names
            headers:
              - expression:
                  jq:
                    expression: header("kafka.KEY") | split("/")[1:] | join("/")
                name: CamelAwsS3Key
              - expression:
                  jq:
                    expression: header("kafka.KEY") | split("/")[0]
                name: CamelAwsS3OverrideBucketName
        - log: "file: ${header.CamelAwsS3Key} - bucket: ${header.CamelAwsS3OverrideBucketName}"
        uri: kamelet:kafka-not-secured-source
      id: filesender-route
  traits:
    camel:
      runtimeVersion: 3.15.2
    container:
      image: ghcr.io/rmortale/camel-k/camel-k-kit-cvmovisaquus73dledmg@sha256:a6ef986588fed3d6f2da3b6b80d8e80d7d9e3031da6dcbb399f370dc143c95f1
    jvm:
      classpath: dependencies/*:dependencies/app/*:dependencies/lib/boot/*:dependencies/lib/main/*:dependencies/quarkus/*
    kamelets:
      list: kafka-not-secured-source,sink
    mount:
      configs:
      - configmap:file-sender
    pull-secret:
      imagePullerDelegation: false
      secretName: registry-secret
status: {}
