apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8scc
  labels:
    app: k8scc
spec:
  selector:
    matchLabels:
      app: k8scc
  template:
    metadata:
      labels:
        app: k8scc
    spec:
      containers:
      - name: k8scc
        image: ghcr.io/rmortale/kustomize-sample-app:91b5080
        ports:
        - containerPort: 8080

