apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: loc-

configMapGenerator:
  - name: k8scc-cm
    envs:
      - env.properties

generatorOptions:
  disableNameSuffixHash: true
  

resources:
- ../../base

patchesStrategicMerge:
  - version.yaml
  - deployment.yaml
