apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: artemis-avt
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: 'artemis-avt-{{name}}'
      namespace: argocd
    spec:
      project: default
      sources:
        - chart: active-mq
          repoURL: https://underndog.github.io/activemq-helm-chart
          targetRevision: 1.6.0
          helm:
            valueFiles:
              - '$values/cluster-resources/artemis-avt/values/{{name}}-values.yaml'
        - repoURL: https://github.com/rmortale/k8s-config.git
          targetRevision: main
          ref: values
      destination:
        server: '{{server}}'
        namespace: artemis
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
      # syncPolicy:
      #   automated:
      #     prune: true
      #     selfHeal: true
       