apiVersion: camel.apache.org/v1
kind: IntegrationPlatform
metadata:
  labels:
    app: camel-k
  name: camel-k
spec:
  build:
    buildConfiguration:
      platforms:
        - linux/amd64
        - linux/arm64
    registry:
      address: ghcr.io/rmortale
      secret: registry-secret
