apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: timer-log
spec:
  flows:
  - route:
      from:
        parameters:
          period: "1000"
        steps:
        - setBody:
            simple: Hello Camel from ${routeId}
        - log: ${body}
        uri: timer:yaml
  traits:
    camel:
      runtimeVersion: 3.15.2
    container:
      image: ghcr.io/rmortale/camel-k/camel-k-kit-cvlfrfek99is73bsenhg@sha256:dd911a09874af6841e70e1c7e6c6a8469dfcd468af627222e1ef9554c0cbf971
    jvm:
      classpath: dependencies/*:dependencies/app/*:dependencies/lib/boot/*:dependencies/lib/main/*:dependencies/quarkus/*
    pull-secret:
      imagePullerDelegation: false
      secretName: registry-secret
status: {}
